Pages/Demo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WeeklyMeals.Data;

namespace WeeklyMeals.Pages
{
    public class DemoModel : PageModel
    {
        private readonly WeeklyMealsContext _context;
        public string Message { get; set; } = "Initial Request";

        public DemoModel(WeeklyMealsContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }

        //Handlers
        public void OnPostView(int id)
        {
            Message = $"View handler fired for {id}";
        }
        //Handlers

        public JsonResult OnGetList()
        {
            var repo = new DemoRepo(_context);

            List<string> lstString;

            lstString = repo.GetDemoList();
                        
            return new JsonResult(lstString);
        }

        public JsonResult OnGetList2()
        {
            List<string> lstString = new List<string>
            {
                "Val from List2",
                "Val Radar",
                "Val Jedi"
            };

            return new JsonResult(lstString);
        }

        public IActionResult OnPostFarfy()
        {
            List<string> lstString = new List<string>
            {
                "Val Pl",
                "Val oo",
                "Val py"
            };
            return new JsonResult(lstString);
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WeeklyMeals.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/GroceryShopping.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WeeklyMeals.Models.WeeklyMealsViewModels;

namespace WeeklyMeals.Pages
{
    public class GroceryShoppingModel : PageModel
    {
        private readonly WeeklyMeals.Data.WeeklyMealsContext _context;

        public GroceryShoppingModel(WeeklyMeals.Data.WeeklyMealsContext context)
        {
            _context = context;
        }

        public List<FoodsGroup> FoodsGroups { get; set; }

        public async Task OnGetAsync()
        {
            var userSettings = await _context.UserSettings.FirstOrDefaultAsync();

            var groceryList = from m in _context.MealPlans
                              join mpr in _context.MealPlanRecipes on m.MealPlanID equals mpr.MealPlanID
                              join r in _context.Recipes on mpr.RecipeID equals r.RecipeID
                              join i in _context.Ingredients on r.RecipeID equals i.Recipe.RecipeID
                              where m.MealPlanID == userSettings.MealPlanID
                              group new { i, mpr } by new
                              {
                                  AisleName = i.Food.GroceryAisle.Name,
                                  FoodName = i.Food.Name,
                                  AmountType = i.SizeType.Name,
                              } into g
                              select new FoodsGroup
                              {
                                  AisleName = g.Key.AisleName,
                                  FoodName = g.Key.FoodName,
                                  AmountType = g.Key.AmountType,
                                  TotalAmount = g.Sum(z => z.i.Size * z.mpr.NumberBatches)
                              } into fg
                              orderby fg.AisleName, fg.FoodName
                              select fg;

            FoodsGroups = groceryList.ToList();
        }
    }
}

Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WeeklyMeals.Data;
using WeeklyMeals.Models;

namespace WeeklyMeals.Pages.Recipes
{
    public class RecipesForMPModel : PageModel
    {
        private readonly WeeklyMeals.Data.WeeklyMealsContext _context;
        public string Message { get; set; } = "Initial Request";
        public double TotalServings { get; set; }
        public string CurrentPlanName { get; set; }

        public RecipesForMPModel(WeeklyMeals.Data.WeeklyMealsContext context)
        {
            _context = context;
        }

        public IList<MealPlan> MealPlans { get; set; }
        public MealPlan MealPlan { get; set; }
        [BindProperty]
        public List<SelectListItem> Options { get; set; }
        [BindProperty]
        public int SelectedMealPlanId { get; set; }
        public MealPlanRecipe MealPlanRecipe { get; set; }
        public int MealCount;

        public async Task OnGetAsync(int SelectedMealPlanId)
        {
            IQueryable<MealPlan> RecipesIQ = _context.MealPlans
                     .Include(e => e.MealPlanRecipes)
                     .ThenInclude(c => c.Recipe);

            var userSettings = await _context.UserSettings.FirstOrDefaultAsync();

            if (SelectedMealPlanId == 0)
            {
                //First time through, they haven't selected, get from UserSettings

                if (userSettings != null)
                {
                    //Read from userSettings
                    SelectedMealPlanId = userSettings.MealPlanID;
                }
            }
            else
            {
                //They selected a mealplan from the dropdown, update UserSettings.MealPlanSelection
                userSettings.MealPlanID = SelectedMealPlanId;

                if (userSettings != null)
                {
                    if (await TryUpdateModelAsync<UserSettings>(
                        userSettings,
                        "",
                        s => s.MealPlanID))
                    {
                        await _context.SaveChangesAsync();
                    }
                }
            }

            //Filter for the selected meal plan id
            //RecipesIQ = RecipesIQ.FirstOrDefault(mp => mp.MealPlanID == SelectedMealPlanId);

            MealPlan = RecipesIQ.FirstOrDefault(mp => mp.MealPlanID == SelectedMealPlanId);
            if (MealPlan != null)
            {
                CurrentPlanName = MealPlan.Name;
            }
            MealPlans = await RecipesIQ.AsNoTracking().ToListAsync();

            //Use linq to sum MealPlanRecipes.NumServings * MealPlanRecipes.PercentForMe
            var mealPlanServings = (from m in _context.MealPlans
                                   join mpr in _context.MealPlanRecipes on m.MealPlanID equals mpr.MealPlanID
                                   join r in _context.Recipes on mpr.RecipeID equals r.RecipeID
                                   where m.MealPlanID == userSettings.MealPlanID
                                   select new
                                   {
                                       r.NumberServings, mpr.NumberBatches, r.PercentForYou
                                   }).ToList();

            TotalServings = mealPlanServings.Select(g => g.NumberBatches * g.NumberServings * g.PercentForYou).Sum();

            //Update the options for mealplan select list
            using (var context = _context)
            {
                //SelectList list = new SelectList([...my collection...], "Value", "Key", SelectedID);
                
                Options = context.MealPlans.Select(a =>
                                            new SelectListItem
                                            {
                                                Value = a.MealPlanID.ToString(),
                                                Text = a.Name,
                                                Selected = (a.MealPlanID == SelectedMealPlanId)
                                            }
                                            ).ToList();

            }

        }

        //When removing a recipe from the meal plan list
        public async Task<IActionResult> OnPostDeleteAsync(int? MealPlanRecipeID)
        {
            if (MealPlanRecipeID == null)
            {
                return NotFound();
            }

            MealPlanRecipe = await _context.MealPlanRecipes.FindAsync(MealPlanRecipeID);

            if (MealPlanRecipe != null)
            {
                _context.MealPlanRecipes.Remove(MealPlanRecipe);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./RecipesForMP");
        }

        public void OnPostCheckDeleteAjax()
        {
            int MealPlanRecipeID = 4;
            MealPlanRecipe mpr = _context.MealPlanRecipes.Find(MealPlanRecipeID);
            var repo = new DemoRepo(_context);
            repo.CheckDelete(MealPlanRecipeID);
        }

        public async Task<IActionResult> OnPostCheckDelete(int? MealPlanRecipeID)
        {
            MealPlanRecipe mpr = _context.MealPlanRecipes.Find(MealPlanRecipeID);

            if (mpr != null)
            {
                if (mpr.NumberBatches == 1)
                {
                    //They want to delete this
                    _context.MealPlanRecipes.Remove(mpr);
                    _context.SaveChanges();
                }
                else
                {
                    //Decrement batch count
                    --mpr.NumberBatches;
                    if (await TryUpdateModelAsync<MealPlanRecipe>(
                        mpr,
                        "",
                        s => s.NumberBatches))
                    {
                        await _context.SaveChangesAsync();
                    }
                }
            }

            return RedirectToPage("./Index");
        }

        public JsonResult OnGetChangeSwitch(int MealPlanID)
        {
            bool roundVal = true;
            var repo = new DemoRepo(_context);

            bool result = repo.UpdateMealRounding(MealPlanID, roundVal);

            return new JsonResult(result);
        }

        public async Task<IActionResult> OnPostCheckAdd(int? MealPlanRecipeID)
        {
            MealPlanRecipe mpr = _context.MealPlanRecipes.Find(MealPlanRecipeID);

            if (mpr != null)
            {
                //Increment batch count
                ++mpr.NumberBatches;
                if (await TryUpdateModelAsync<MealPlanRecipe>(
                    mpr,
                    "",
                    s => s.NumberBatches))
                {
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/IndexOrig.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WeeklyMeals.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WeeklyMeals.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/WeekendPrep.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WeeklyMeals.Models.WeeklyMealsViewModels;

namespace WeeklyMeals.Pages.MealPlans
{
    public class WeekendPrepModel : PageModel
    {
        private readonly WeeklyMeals.Data.WeeklyMealsContext _context;
      
        public WeekendPrepModel(WeeklyMeals.Data.WeeklyMealsContext context)
        {
            _context = context;
        }

        public List<FoodsGroup> FoodsGroups { get; set; }

        public async Task OnGetAsync()
        {
            var userSettings = await _context.UserSettings.FirstOrDefaultAsync();
            FoodsGroups = await _context.MealPlans
                .Where(m => m.MealPlanID == userSettings.MealPlanID)
                .SelectMany(x => x.MealPlanRecipes)
                .SelectMany(y => y.Recipe.Ingredients)
                .Where(z => z.PrepTypeID != 0 && !z.PrepType.Name.Equals("No prep"))
                .OrderBy(x => x.Food.GroceryAisle.Name)
                .ThenBy(x => x.Food.Name)
                .GroupBy(x => new { Aisle = x.Food.GroceryAisle.Name, Food = x.Food.Name, MsType = x.SizeType.Name, Prep = x.PrepType.Name })
                .Select(x => new FoodsGroup { AisleName = x.Key.Aisle, FoodName = x.Key.Food, AmountType = x.Key.MsType, TotalAmount = x.Sum(y => y.Size), PrepType = x.Key.Prep })
                .ToListAsync();

        }
    }
}

Pages/Demo.cshtml
@page
@model WeeklyMeals.Pages.DemoModel
@{
}
<h3>DeMo</h3>

<h3 class="clearfix">@Model.Message</h3>

<div class="col-lg-1">
    <form asp-page-handler="delete" asp-route-id="10" method="post">
        <button class="btn btn-default">Delete</button>
    </form>
</div>

<div class="col-lg-1">
    <form asp-page-handler="view" method="post">
        <button class="btn btn-default">View</button>
        <input type="hidden" name="id" value="3" />
    </form>
</div>

<div class="number">
    <span class="minus">-</span>
    <input type="text" value="1" />
    <span class="plus">+</span>
</div>

    dvPostItems:
<div id="dvPostItems" style="font-size:24px; color:lightgreen;">
    Initialized Value
</div>

<button id="btnTestRead" class="btn btn-danger">Test Read</button>

<form action="" method="Post">
    <button id="btnTestPost" type="submit" class="btn btn-info">Test Post</button>
</form>

<form action="/Demo" method="Post">
    <div class="form-group">
        <div class="control-label col-md-2" style="color:sandybrown;">dvItems</div>
        <div class="col-md-5" style="color:sandybrown;" id="dvItems"></div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</form>

@section Scripts
{
    <script>
        $('#btnTestPost').on('click', function (e) {
            e.preventDefault();
            var dvItems = $("#dvPostItems");
            dvItems.empty();
            $.ajax({
                type: "POST",
                url: "/Demo?handler=Farfy",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-TOKEN",
                        $('input:hidden[name="__RequestVerificationToken"]').val());
                },
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $.each(response, function (i, item) {
                        var $tr = $('<li>').append(item).appendTo(dvItems);
                    });
                    alert('success');
                    return false;
                },
                failure: function (response) {
                    alert(response);
                }
            });
        });

        $('#btnTestRead').on('click', function () {
            $.ajax({
                type: "GET",
                url: "/Demo?handler=List2",
                contentType: "application/json",
                dataType: "json",
                success: function (response) {
                    var dvItems = $("#dvItems");
                    dvItems.empty();
                    $.each(response, function (i, item) {
                        var $tr = $('<li>').append(item).appendTo(dvItems);
                    });
                },
                failure: function (response) {
                    alert(response);
                }
            });
        });
    </script>
}

Pages/GroceryShopping.cshtml
@page
@using WeeklyMeals.Models.WeeklyMealsViewModels
@model WeeklyMeals.Pages.GroceryShoppingModel
@{
}
@{
    ViewData["Title"] = "Grocery List";
}
@functions {

    public static string FormatMeasurement(double Amount, string SizeType, string Food)
    {
        string numberFormat = "{0:0.0} {1}";
        if (Amount % 1 <= .1)
        {
            numberFormat = "{0:0} {1}";
        }
        if (Amount > 1 && !Food.EndsWith("s"))
        {
            numberFormat += "s";
        }
        if (SizeType.Equals("each"))
        {
            return string.Format(numberFormat, Amount, Food);
        }
        else
        {
            return string.Format(numberFormat + " {2}", Amount, SizeType, Food);
        }
    }
}
<div style="background-color:white;">
    <div class="ml-5">

        <h3>Grocery List</h3>

        <table class="table table-borderless">
            <tbody>
                @{ string tempAisle = ""; int ingredCounter = 1; string temp = ""; }
                @foreach (var item in Model.FoodsGroups)
                {
                    if (!item.AisleName.Equals(tempAisle))
                    {
                        <tr>
                            @if (!item.AisleName.Equals(tempAisle))
                            {
                                ingredCounter = 1;
                                <td>
                                    <header class="ingredients-header px-2 py-2" style="text-transform: uppercase">
                                        @Html.DisplayFor(modelItem => item.AisleName)
                                    </header>
                                </td>
                                tempAisle = item.AisleName;
                            }
                        </tr>
                    }
                    <tr>
                        <!-- Food name-->
                        @if (ingredCounter % 2 == 1)
                        {
                            temp = "tr-odd";
                        }
                        else
                        {
                            temp = "";
                        }
                        <td class=@temp>
                            <div class="grocery-list-component-item">
                                @FormatMeasurement(item.TotalAmount, item.AmountType, item.FoodName)
                            </div>
                        </td>
                    </tr>
                    ingredCounter++;
                }
            </tbody>
        </table>
    </div>
</div>

Pages/Index.cshtml
@page
@model WeeklyMeals.Pages.Recipes.RecipesForMPModel

@{
    ViewData["Title"] = "Meal Plans";
}

<div style="padding-bottom: 10px; padding-left:40px; box-shadow: 0 5px 10px rgba(0,0,0,.1);" class="pt-4">
    <form asp-page="./Index" method="get">
        <div class="form-inline no-color">
            <select class="col-md-2" asp-for="SelectedMealPlanId" asp-items="Model.Options">
                <option value="">Pick your meal plan</option>
            </select>
            <input type="submit" class="col-md-1" color: #5cb8b2;" value="Select" />
            <div class="custom-control custom-switch col-md-1 offset-md-1">
                <input asp-for="@Model.MealPlan.RoundOutMeals" type="checkbox" class="custom-control-input" id="customSwitches">
                <label class="custom-control-label" for="customSwitches">Round out meals</label>
            </div>
            <input type="text" id="MealPlanIDField" value="@Model.MealPlan.MealPlanID" />
             <div class="text-location col-md-2">
                <div class="tbsmall">MEAL PLAN</div>
                <div class="title">@Model.CurrentPlanName</div>
            </div>
            <span class="totalservings">@Model.TotalServings</span>
            <div class="tbsmall" style="margin-left: 4px;">SERVINGS</div>
            <div class="col-md-3">
                <a asp-page="/Recipes/ChooseRecipe" class="btn btn-primary m-1">Add a new recipe</a>
            </div>
        </div>
    </form>
</div>

<div class="row" style="margin-left: 100px; margin-right: 100px; margin-top: 40px;">
    @foreach (var recipe in Model.MealPlan.MealPlanRecipes)
    {
        <div style="margin-bottom:30px; width: 22%; margin-left: 14px;">
            <div class="card">
                <div class="card-body">
                    <a class="title" asp-page="/Recipes/Details" asp-route-ID="@recipe.Recipe.RecipeID">@recipe.Recipe.Name</a>
                    <div class="recipe-additional-info">#Servings: @recipe.Recipe.NumberServings</div>
                    <form method="post">
                        <span class="recipe-additional-info">#Batches: </span>
                        <input type="submit" value="-" asp-page-handler="CheckDelete" asp-route-MealPlanRecipeID="@recipe.MealPlanRecipeID" class="minus" />
                        <span class="plusminusinput">@recipe.NumberBatches</span>
                        <input type="submit" value="+" asp-page-handler="CheckAdd" asp-route-MealPlanRecipeID="@recipe.MealPlanRecipeID" class="plus" />
                    </form>
                    @if (recipe.Recipe.PercentForYou < 1)
                    {
                        <div class="recipe-additional-info">Percent for you: @string.Format("{0:0}%", recipe.Recipe.PercentForYou * 100)</div>
                    }
                </div>
                <img class="card-img-bot" src="@Url.Content(@recipe.Recipe.ImageUrl)" />
            </div>
        </div>
    }
</div>

@section Scripts
{
    <script>
        $('#customSwitches').on('change', function (e) {
            e.preventDefault(); //Prevents form refresh
            var MealPlanIDValue = $("#MealPlanIDField").val();
            $.ajax({
                type: "GET",
                data: {
                    MealPlanID: MealPlanIDValue
                },
                url: "/Index?handler=ChangeSwitch",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    alert('success');
                },
                failure: function (response) {
                    alert('failure');
                }
            });
        });
           
            $('.dropdown-content').on('click', function () {
                alert('here');
                alert(this.href);
                e.preventDefault();
            });

            $('#minusbutton').on('click', function (e) {
                alert('onclick');
                e.preventDefault(); //Prevents form refresh
                $.ajax({
                    type: "POST",
                    url: "/Demo?handler=CheckDeleteAjax",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                        alert(success);
                    },
                    failure: function (response) {
                        alert(response);
                    }
                });
            });
    </script>
}

Pages/IndexOrig.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/WeekendPrep.cshtml
@page
@model WeeklyMeals.Pages.MealPlans.WeekendPrepModel
@using WeeklyMeals.Models.WeeklyMealsViewModels
@{
}

@{
}
@{
    ViewData["Title"] = "Weekend Prep";
}
@functions {

    public static string FormatMeasurement(double Amount, string SizeType, string Food)
    {
        string numberFormat = "{0:0.0} {1}";
        if (Amount % 1 <= .1)
        {
            numberFormat = "{0:0} {1}";
        }
        if (Amount > 1 && !Food.EndsWith("s"))
        {
            numberFormat += "s";
        }
        if (SizeType.Equals("each"))
        {
            return string.Format(numberFormat, Amount, Food);
        }
        else
        {
            return string.Format(numberFormat + " {2}", Amount, SizeType, Food);
        }
    }
}

<div style="background-color:white;">
    <div class="ml-5">

        <h3>Prep</h3>

        @{ int ingredCounter = 0; string temp = ""; }
        <table class="table table-borderless">
            <tbody>
                <tr>
                    <td>
                        <header class="ingredients-header px-2 py-2" style="text-transform: uppercase">
                            Chop
                        </header>
                    </td>
                </tr>
                @foreach (var item in Model.FoodsGroups)
                {
                    <tr>
                        @if (ingredCounter % 2 == 1)
                        {
                            temp = "tr-odd";
                        }
                        else
                        {
                            temp = "";
                        }
                        <td class=@temp>
                            <div class="grocery-list-component-item">
                                @FormatMeasurement(item.TotalAmount, item.AmountType, item.FoodName),
                                @Html.DisplayFor(i => item.PrepType)
                            </div>
                        </td>
                    </tr>
                    ingredCounter++;
                }

            </tbody>
        </table>

    </div>
</div>